export const DEFAULT_FAQS = [
  {
    id: "faq-1",
    question: "How do I book an appointment?",
    answer: "You can book an appointment through our website by clicking the 'Book Appointment' button, calling our helpline, or visiting the hospital directly. Our team will confirm your appointment via WhatsApp or email.",
    category: "Appointments",
    order: 1,
    isActive: true,
  },
  {
    id: "faq-2",
    question: "What are the hospital's OPD timings?",
    answer: "Our General OPD is open Monday to Saturday. Exact timings may vary by doctor and department — please check the specific doctor's schedule on our Doctors page or contact us to confirm current hours.",
    category: "OPD & Timings",
    order: 2,
    isActive: true,
  },
  {
    id: "faq-3",
    question: "Do I need an appointment to see an eye specialist?",
    answer: "While walk-ins are welcome, we recommend booking an appointment in advance to minimize your waiting time and ensure the doctor you wish to see is available.",
    category: "Appointments",
    order: 3,
    isActive: true,
  },
  {
    id: "faq-4",
    question: "How much does cataract surgery cost?",
    answer: "Cataract surgery costs vary depending on the type of lens and procedure required. Please contact our hospital directly or book a consultation for a personalized cost estimate.",
    category: "Cataract & Surgery",
    order: 4,
    isActive: true,
  },
  {
    id: "faq-5",
    question: "How long does cataract surgery take?",
    answer: "Cataract surgery is typically a quick outpatient procedure, usually completed within 15–30 minutes per eye, though this can vary based on individual cases.",
    category: "Cataract & Surgery",
    order: 5,
    isActive: true,
  },
  {
    id: "faq-6",
    question: "How long is recovery after cataract surgery?",
    answer: "Most patients notice improved vision within a few days, with full recovery typically taking a few weeks. Your surgeon will give you specific aftercare instructions based on your case.",
    category: "Cataract & Surgery",
    order: 6,
    isActive: true,
  },
  {
    id: "faq-7",
    question: "Does the hospital treat children with eye problems?",
    answer: "Yes, we provide pediatric eye care services, including vision assessments and treatment for common childhood eye conditions.",
    category: "Services & Care",
    order: 7,
    isActive: true,
  },
  {
    id: "faq-8",
    question: "Do you provide emergency eye care?",
    answer: "Yes, we offer 24/7 emergency eye care services. Please call our emergency helpline immediately if you experience a sudden eye injury or vision problem.",
    category: "Emergency Care",
    order: 8,
    isActive: true,
  },
  {
    id: "faq-9",
    question: "Which diagnostic tests are available?",
    answer: "We offer a comprehensive range of diagnostic services including OCT, visual field testing, biometry, corneal topography, and more. Visit our Diagnostic Services page for the full list.",
    category: "Services & Care",
    order: 9,
    isActive: true,
  },
  {
    id: "faq-10",
    question: "Where is Haji Murad Eye Hospital Trust located?",
    answer: "Haji Murad Eye Hospital Trust is conveniently located at Upper Chanab, Canal Bank, G.T Road, Gujranwala. We are easily accessible from all major routes in Gujranwala.",
    category: "General",
    order: 10,
    isActive: true,
  },
];
